#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: link_starteragent2d_v2_compat_2d.sh [options]

Creates or refreshes compatibility links so the legacy starter-stack launch
scripts can execute binaries built from the maintained StarterAgent2D-V2 tree.

Options:
  --agent-dir DIR   Path to StarterAgent2D-V2 source root. The script will
                    look for build/bin or build-linux/bin under it.
  --bin-dir DIR     Path to a built StarterAgent2D-V2 bin directory.
  --lib-dir DIR     Path to the librcsc shared-library directory used at
                    runtime. Defaults to ~/local/starter/lib when present.
  --force           Replace existing sample_* binaries/symlinks in Agent/src.
  --dry-run         Print planned changes without modifying files.
  -h, --help        Show this help.

Typical usage:
  ./link_starteragent2d_v2_compat_2d.sh --force
  ./link_starteragent2d_v2_compat_2d.sh --agent-dir ../StarterAgent2D-V2 --force
  ./link_starteragent2d_v2_compat_2d.sh --bin-dir ../StarterAgent2D-V2/build/bin --lib-dir "$HOME/local/starter/lib" --force
EOF
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TARGET_DIR="${SCRIPT_DIR}/Agent/src"
COMPAT_ENV_FILE="${TARGET_DIR}/.starteragent2d_v2_compat.env"

agent_dir=""
bin_dir=""
lib_dir=""
force=0
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent-dir)
      agent_dir="$2"
      shift 2
      ;;
    --bin-dir)
      bin_dir="$2"
      shift 2
      ;;
    --lib-dir)
      lib_dir="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

canonical_dir() {
  cd "$1" >/dev/null 2>&1 && pwd -P
}

detect_agent_bin_dir() {
  local candidate
  local -a candidates=()

  if [[ -n "${agent_dir}" ]]; then
    candidates+=(
      "${agent_dir}/build/bin"
      "${agent_dir}/build-linux/bin"
    )
  fi

  candidates+=(
    "${SCRIPT_DIR}/../StarterAgent2D-V2/build/bin" \
    "${SCRIPT_DIR}/../StarterAgent2D-V2/build-linux/bin"
  )

  for candidate in "${candidates[@]}"; do
    if [[ -d "${candidate}" ]]; then
      printf '%s\n' "$(canonical_dir "${candidate}")"
      return 0
    fi
  done
  return 1
}

detect_lib_dir_from_binary() {
  local detected
  detected="$(ldd "${bin_dir}/sample_player" 2>/dev/null | awk '/librcsc/ { print $3; exit }')"
  if [[ -n "${detected}" && -f "${detected}" ]]; then
    dirname "${detected}"
    return 0
  fi
  return 1
}

require_runtime_binary() {
  local name="$1"
  if [[ ! -x "${bin_dir}/${name}" ]]; then
    echo "Missing ${name} in ${bin_dir}" >&2
    exit 1
  fi
}

link_binary() {
  local name="$1"
  local target="${bin_dir}/${name}"
  local dest="${TARGET_DIR}/${name}"

  if [[ -e "${dest}" && ! -L "${dest}" && "${force}" -ne 1 ]]; then
    echo "Refusing to replace existing non-symlink ${dest}. Re-run with --force." >&2
    exit 1
  fi

  if [[ "${dry_run}" -eq 1 ]]; then
    echo "Would link ${dest} -> ${target}"
    return 0
  fi

  if [[ -e "${dest}" || -L "${dest}" ]]; then
    rm -f "${dest}"
  fi
  ln -s "${target}" "${dest}"
}

write_compat_env() {
  if [[ "${dry_run}" -eq 1 ]]; then
    echo "Would write ${COMPAT_ENV_FILE} with STARTER_LIBRCSC_LIB_DIR=${lib_dir}"
    return 0
  fi

  {
    echo "# Auto-generated by link_starteragent2d_v2_compat_2d.sh"
    printf 'STARTER_AGENT2D_V2_BIN_DIR=%q\n' "${bin_dir}"
    printf 'STARTER_LIBRCSC_LIB_DIR=%q\n' "${lib_dir}"
  } > "${COMPAT_ENV_FILE}"
}

if [[ -n "${bin_dir}" ]]; then
  if [[ ! -d "${bin_dir}" ]]; then
    echo "--bin-dir does not exist: ${bin_dir}" >&2
    exit 1
  fi
  bin_dir="$(canonical_dir "${bin_dir}")"
else
  if [[ -n "${agent_dir}" && ! -d "${agent_dir}" ]]; then
    echo "--agent-dir does not exist: ${agent_dir}" >&2
    exit 1
  fi
  if ! bin_dir="$(detect_agent_bin_dir)"; then
    echo "Could not find a StarterAgent2D-V2 build/bin directory." >&2
    echo "Checked the default sibling location under environment/2d-environment/StarterAgent2D-V2." >&2
    echo "Pass --agent-dir or --bin-dir explicitly." >&2
    exit 1
  fi
fi

require_runtime_binary sample_player
require_runtime_binary sample_coach
require_runtime_binary sample_trainer

if [[ -z "${lib_dir}" ]]; then
  if [[ -d "${HOME}/local/starter/lib" ]]; then
    lib_dir="$(canonical_dir "${HOME}/local/starter/lib")"
  elif detected_lib_dir="$(detect_lib_dir_from_binary)"; then
    lib_dir="${detected_lib_dir}"
  else
    echo "Could not determine the librcsc shared-library directory." >&2
    echo "Pass --lib-dir explicitly, for example --lib-dir \"\$HOME/local/starter/lib\"." >&2
    exit 1
  fi
else
  if [[ ! -d "${lib_dir}" ]]; then
    echo "--lib-dir does not exist: ${lib_dir}" >&2
    exit 1
  fi
  lib_dir="$(canonical_dir "${lib_dir}")"
fi

link_binary sample_player
link_binary sample_coach
link_binary sample_trainer
write_compat_env

if [[ "${dry_run}" -eq 0 ]]; then
  echo "Linked StarterAgent2D-V2 runtime binaries into ${TARGET_DIR}"
  echo "Wrote runtime library settings to ${COMPAT_ENV_FILE}"
fi
